blueprint:
    name: Cambio de estado de puerta
    description: Avisar de que una puerta cambió de estado. Para usar es necesario cambiar la variable "sensores" a la lista de sensores de las puertas y "alarmado" a un ayudante booleano
    domain: automation
    author: cristianrguez8

alias: Cambio de estado de puerta
description: Avisar de que una puerta cambió de estado
triggers:
  - trigger: state
    entity_id:
        {{sensores}}
    to:
conditions:
  - condition: state
    entity_id: {{alarmado}}
    state: "on"
actions:
    - variables:
        titulo: >
            {% if trigger.to_state.state == 'off' %}
                Uf, menos mal
            {% elif trigger.to_state.state == 'on' %}
                Ojo cuidao!
            {% else %}
                Bueno carallo!
            {% endif %}
        estado: >
            {% if trigger.to_state.state == 'off' %}
                Ya se ha cerrado
            {% elif trigger.to_state.state == 'on' %}
                Se ha abierto
            {% else %}
                Ya se ha muerto
            {% endif %}
    - service: script.enviar_notificacion_con_etiqueta
      data:
        titulo: "{{ titulo }}"
        mensaje: >
            {{ estado }} {{ trigger.to_state.name }}
        etiqueta: "Alarmas"
mode: single
